/**
 * Plugins/SeamlessFieldFlight/FieldAdjacency.js
 *
 * AUTO-GENERATED by tools/gen-field-adjacency.mjs — do not edit by hand.
 * Field-to-field adjacency derived from rAthena border-warp scripts.
 * Keyed by bare lowercase map name. `dst` is the server drop point;
 * `offset` is an approximate dst-origin offset (cells) for stitched render.
 */

const FieldAdjacency = {
	"cmd_fild01": {
		"neighbors": [
			{
				"dir": "S",
				"map": "cmd_fild02",
				"dst": {
					"x": 222,
					"y": 372
				},
				"edge": {
					"axis": "y",
					"at": 24,
					"cross": [
						222,
						222
					]
				},
				"offset": {
					"dx": 0,
					"dy": -348
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "cmd_fild03",
				"dst": {
					"x": 27,
					"y": 68
				},
				"edge": {
					"axis": "x",
					"at": 362,
					"cross": [
						73,
						263
					]
				},
				"offset": {
					"dx": 335,
					"dy": 5
				},
				"warps": 2
			},
			{
				"dir": "N",
				"map": "um_fild03",
				"dst": {
					"x": 114,
					"y": 53
				},
				"edge": {
					"axis": "y",
					"at": 366,
					"cross": [
						77,
						178
					]
				},
				"offset": {
					"dx": -37,
					"dy": 313
				},
				"warps": 2
			}
		]
	},
	"cmd_fild02": {
		"neighbors": [
			{
				"dir": "N",
				"map": "cmd_fild01",
				"dst": {
					"x": 222,
					"y": 30
				},
				"edge": {
					"axis": "y",
					"at": 376,
					"cross": [
						222,
						222
					]
				},
				"offset": {
					"dx": 0,
					"dy": 346
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "cmd_fild04",
				"dst": {
					"x": 25,
					"y": 275
				},
				"edge": {
					"axis": "x",
					"at": 382,
					"cross": [
						95,
						269
					]
				},
				"offset": {
					"dx": 357,
					"dy": -6
				},
				"warps": 2
			}
		]
	},
	"cmd_fild03": {
		"neighbors": [
			{
				"dir": "W",
				"map": "cmd_fild01",
				"dst": {
					"x": 359,
					"y": 260
				},
				"edge": {
					"axis": "x",
					"at": 23,
					"cross": [
						68,
						269
					]
				},
				"offset": {
					"dx": -336,
					"dy": 9
				},
				"warps": 2
			},
			{
				"dir": "S",
				"map": "cmd_fild04",
				"dst": {
					"x": 181,
					"y": 367
				},
				"edge": {
					"axis": "y",
					"at": 17,
					"cross": [
						181,
						181
					]
				},
				"offset": {
					"dx": 0,
					"dy": -350
				},
				"warps": 1
			}
		]
	},
	"cmd_fild04": {
		"neighbors": [
			{
				"dir": "W",
				"map": "cmd_fild02",
				"dst": {
					"x": 378,
					"y": 264
				},
				"edge": {
					"axis": "x",
					"at": 21,
					"cross": [
						92,
						275
					]
				},
				"offset": {
					"dx": -357,
					"dy": 11
				},
				"warps": 2
			},
			{
				"dir": "E",
				"map": "cmd_fild06",
				"dst": {
					"x": 26,
					"y": 288
				},
				"edge": {
					"axis": "x",
					"at": 376,
					"cross": [
						287,
						287
					]
				},
				"offset": {
					"dx": 350,
					"dy": -1
				},
				"warps": 1
			},
			{
				"dir": "N",
				"map": "cmd_fild03",
				"dst": {
					"x": 183,
					"y": 23
				},
				"edge": {
					"axis": "y",
					"at": 372,
					"cross": [
						180,
						180
					]
				},
				"offset": {
					"dx": -3,
					"dy": 349
				},
				"warps": 1
			}
		]
	},
	"cmd_fild06": {
		"neighbors": [
			{
				"dir": "W",
				"map": "cmd_fild04",
				"dst": {
					"x": 371,
					"y": 288
				},
				"edge": {
					"axis": "x",
					"at": 21,
					"cross": [
						285,
						285
					]
				},
				"offset": {
					"dx": -350,
					"dy": -3
				},
				"warps": 1
			},
			{
				"dir": "S",
				"map": "cmd_fild07",
				"dst": {
					"x": 147,
					"y": 370
				},
				"edge": {
					"axis": "y",
					"at": 27,
					"cross": [
						151,
						151
					]
				},
				"offset": {
					"dx": 4,
					"dy": -343
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "cmd_fild08",
				"dst": {
					"x": 25,
					"y": 102
				},
				"edge": {
					"axis": "x",
					"at": 368,
					"cross": [
						96,
						359
					]
				},
				"offset": {
					"dx": 343,
					"dy": -6
				},
				"warps": 3
			}
		]
	},
	"cmd_fild07": {
		"neighbors": [
			{
				"dir": "N",
				"map": "cmd_fild06",
				"dst": {
					"x": 147,
					"y": 36
				},
				"edge": {
					"axis": "y",
					"at": 379,
					"cross": [
						149,
						149
					]
				},
				"offset": {
					"dx": 2,
					"dy": 343
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "cmd_fild09",
				"dst": {
					"x": 18,
					"y": 170
				},
				"edge": {
					"axis": "x",
					"at": 389,
					"cross": [
						186,
						186
					]
				},
				"offset": {
					"dx": 371,
					"dy": 16
				},
				"warps": 1
			}
		]
	},
	"cmd_fild08": {
		"neighbors": [
			{
				"dir": "W",
				"map": "cmd_fild06",
				"dst": {
					"x": 366,
					"y": 359
				},
				"edge": {
					"axis": "x",
					"at": 25,
					"cross": [
						102,
						355
					]
				},
				"offset": {
					"dx": -341,
					"dy": -4
				},
				"warps": 3
			},
			{
				"dir": "S",
				"map": "cmd_fild09",
				"dst": {
					"x": 76,
					"y": 375
				},
				"edge": {
					"axis": "y",
					"at": 31,
					"cross": [
						76,
						309
					]
				},
				"offset": {
					"dx": 0,
					"dy": -344
				},
				"warps": 2
			},
			{
				"dir": "E",
				"map": "moc_fild12",
				"dst": {
					"x": 26,
					"y": 305
				},
				"edge": {
					"axis": "x",
					"at": 354,
					"cross": [
						324,
						324
					]
				},
				"offset": {
					"dx": 328,
					"dy": 19
				},
				"warps": 1
			}
		]
	},
	"cmd_fild09": {
		"neighbors": [
			{
				"dir": "W",
				"map": "cmd_fild07",
				"dst": {
					"x": 382,
					"y": 184
				},
				"edge": {
					"axis": "x",
					"at": 12,
					"cross": [
						170,
						170
					]
				},
				"offset": {
					"dx": -370,
					"dy": -14
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "moc_fild18",
				"dst": {
					"x": 55,
					"y": 170
				},
				"edge": {
					"axis": "x",
					"at": 369,
					"cross": [
						164,
						164
					]
				},
				"offset": {
					"dx": 314,
					"dy": -6
				},
				"warps": 1
			},
			{
				"dir": "N",
				"map": "cmd_fild08",
				"dst": {
					"x": 309,
					"y": 60
				},
				"edge": {
					"axis": "y",
					"at": 381,
					"cross": [
						75,
						309
					]
				},
				"offset": {
					"dx": 0,
					"dy": 321
				},
				"warps": 2
			}
		]
	},
	"dic_fild01": {
		"neighbors": [
			{
				"dir": "S",
				"map": "dic_fild02",
				"dst": {
					"x": 70,
					"y": 373
				},
				"edge": {
					"axis": "y",
					"at": 23,
					"cross": [
						69,
						69
					]
				},
				"offset": {
					"dx": -1,
					"dy": -350
				},
				"warps": 1
			}
		]
	},
	"dic_fild02": {
		"neighbors": [
			{
				"dir": "N",
				"map": "dic_fild01",
				"dst": {
					"x": 69,
					"y": 25
				},
				"edge": {
					"axis": "y",
					"at": 375,
					"cross": [
						71,
						71
					]
				},
				"offset": {
					"dx": 2,
					"dy": 350
				},
				"warps": 1
			}
		]
	},
	"ein_fild01": {
		"neighbors": [
			{
				"dir": "S",
				"map": "ein_fild05",
				"dst": {
					"x": 172,
					"y": 366
				},
				"edge": {
					"axis": "y",
					"at": 34,
					"cross": [
						106,
						234
					]
				},
				"offset": {
					"dx": -66,
					"dy": -332
				},
				"warps": 2
			}
		]
	},
	"ein_fild03": {
		"neighbors": [
			{
				"dir": "E",
				"map": "ein_fild04",
				"dst": {
					"x": 22,
					"y": 251
				},
				"edge": {
					"axis": "x",
					"at": 363,
					"cross": [
						204,
						257
					]
				},
				"offset": {
					"dx": 341,
					"dy": 6
				},
				"warps": 3
			},
			{
				"dir": "S",
				"map": "lhz_fild02",
				"dst": {
					"x": 166,
					"y": 365
				},
				"edge": {
					"axis": "y",
					"at": 32,
					"cross": [
						142,
						142
					]
				},
				"offset": {
					"dx": -24,
					"dy": -333
				},
				"warps": 1
			}
		]
	},
	"ein_fild04": {
		"neighbors": [
			{
				"dir": "E",
				"map": "ein_fild05",
				"dst": {
					"x": 80,
					"y": 294
				},
				"edge": {
					"axis": "x",
					"at": 343,
					"cross": [
						293,
						293
					]
				},
				"offset": {
					"dx": 263,
					"dy": -1
				},
				"warps": 1
			},
			{
				"dir": "W",
				"map": "ein_fild03",
				"dst": {
					"x": 361,
					"y": 257
				},
				"edge": {
					"axis": "x",
					"at": 20,
					"cross": [
						205,
						251
					]
				},
				"offset": {
					"dx": -341,
					"dy": -6
				},
				"warps": 3
			}
		]
	},
	"ein_fild05": {
		"neighbors": [
			{
				"dir": "W",
				"map": "ein_fild04",
				"dst": {
					"x": 336,
					"y": 292
				},
				"edge": {
					"axis": "x",
					"at": 76,
					"cross": [
						294,
						294
					]
				},
				"offset": {
					"dx": -260,
					"dy": 2
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "ein_fild06",
				"dst": {
					"x": 47,
					"y": 166
				},
				"edge": {
					"axis": "x",
					"at": 376,
					"cross": [
						183,
						183
					]
				},
				"offset": {
					"dx": 329,
					"dy": 17
				},
				"warps": 1
			},
			{
				"dir": "N",
				"map": "ein_fild01",
				"dst": {
					"x": 106,
					"y": 40
				},
				"edge": {
					"axis": "y",
					"at": 371,
					"cross": [
						172,
						172
					]
				},
				"offset": {
					"dx": 66,
					"dy": 331
				},
				"warps": 1
			}
		]
	},
	"ein_fild06": {
		"neighbors": [
			{
				"dir": "W",
				"map": "ein_fild05",
				"dst": {
					"x": 371,
					"y": 183
				},
				"edge": {
					"axis": "x",
					"at": 42,
					"cross": [
						171,
						171
					]
				},
				"offset": {
					"dx": -329,
					"dy": -12
				},
				"warps": 1
			},
			{
				"dir": "N",
				"map": "yuno_fild04",
				"dst": {
					"x": 251,
					"y": 23
				},
				"edge": {
					"axis": "y",
					"at": 365,
					"cross": [
						252,
						252
					]
				},
				"offset": {
					"dx": 1,
					"dy": 342
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "yuno_fild07",
				"dst": {
					"x": 75,
					"y": 219
				},
				"edge": {
					"axis": "x",
					"at": 340,
					"cross": [
						94,
						170
					]
				},
				"offset": {
					"dx": 265,
					"dy": -49
				},
				"warps": 2
			},
			{
				"dir": "S",
				"map": "ein_fild07",
				"dst": {
					"x": 147,
					"y": 360
				},
				"edge": {
					"axis": "y",
					"at": 35,
					"cross": [
						135,
						135
					]
				},
				"offset": {
					"dx": -12,
					"dy": -325
				},
				"warps": 1
			}
		]
	},
	"ein_fild07": {
		"neighbors": [
			{
				"dir": "E",
				"map": "yuno_fild11",
				"dst": {
					"x": 30,
					"y": 266
				},
				"edge": {
					"axis": "x",
					"at": 382,
					"cross": [
						263,
						263
					]
				},
				"offset": {
					"dx": 352,
					"dy": -3
				},
				"warps": 1
			},
			{
				"dir": "N",
				"map": "ein_fild06",
				"dst": {
					"x": 135,
					"y": 37
				},
				"edge": {
					"axis": "y",
					"at": 362,
					"cross": [
						145,
						145
					]
				},
				"offset": {
					"dx": 10,
					"dy": 325
				},
				"warps": 1
			},
			{
				"dir": "S",
				"map": "ein_fild10",
				"dst": {
					"x": 194,
					"y": 370
				},
				"edge": {
					"axis": "y",
					"at": 42,
					"cross": [
						191,
						191
					]
				},
				"offset": {
					"dx": -3,
					"dy": -328
				},
				"warps": 1
			}
		]
	},
	"ein_fild08": {
		"neighbors": [
			{
				"dir": "E",
				"map": "ein_fild09",
				"dst": {
					"x": 36,
					"y": 132
				},
				"edge": {
					"axis": "x",
					"at": 363,
					"cross": [
						128,
						128
					]
				},
				"offset": {
					"dx": 327,
					"dy": -4
				},
				"warps": 1
			},
			{
				"dir": "W",
				"map": "lhz_fild03",
				"dst": {
					"x": 361,
					"y": 283
				},
				"edge": {
					"axis": "x",
					"at": 23,
					"cross": [
						275,
						275
					]
				},
				"offset": {
					"dx": -338,
					"dy": -8
				},
				"warps": 1
			}
		]
	},
	"ein_fild09": {
		"neighbors": [
			{
				"dir": "E",
				"map": "ein_fild10",
				"dst": {
					"x": 26,
					"y": 331
				},
				"edge": {
					"axis": "x",
					"at": 329,
					"cross": [
						346,
						346
					]
				},
				"offset": {
					"dx": 303,
					"dy": 15
				},
				"warps": 1
			},
			{
				"dir": "W",
				"map": "ein_fild08",
				"dst": {
					"x": 361,
					"y": 128
				},
				"edge": {
					"axis": "x",
					"at": 34,
					"cross": [
						132,
						132
					]
				},
				"offset": {
					"dx": -327,
					"dy": 4
				},
				"warps": 1
			}
		]
	},
	"ein_fild10": {
		"neighbors": [
			{
				"dir": "N",
				"map": "ein_fild07",
				"dst": {
					"x": 191,
					"y": 44
				},
				"edge": {
					"axis": "y",
					"at": 372,
					"cross": [
						194,
						194
					]
				},
				"offset": {
					"dx": 3,
					"dy": 328
				},
				"warps": 1
			},
			{
				"dir": "W",
				"map": "ein_fild09",
				"dst": {
					"x": 327,
					"y": 346
				},
				"edge": {
					"axis": "x",
					"at": 24,
					"cross": [
						331,
						331
					]
				},
				"offset": {
					"dx": -303,
					"dy": -15
				},
				"warps": 1
			}
		]
	},
	"gef_fild00": {
		"neighbors": [
			{
				"dir": "N",
				"map": "mjolnir_06",
				"dst": {
					"x": 265,
					"y": 32
				},
				"edge": {
					"axis": "y",
					"at": 382,
					"cross": [
						267,
						267
					]
				},
				"offset": {
					"dx": 2,
					"dy": 350
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "prt_fild00",
				"dst": {
					"x": 24,
					"y": 125
				},
				"edge": {
					"axis": "x",
					"at": 381,
					"cross": [
						137,
						137
					]
				},
				"offset": {
					"dx": 357,
					"dy": 12
				},
				"warps": 1
			}
		]
	},
	"gef_fild01": {
		"neighbors": [
			{
				"dir": "E",
				"map": "prt_fild04",
				"dst": {
					"x": 20,
					"y": 114
				},
				"edge": {
					"axis": "x",
					"at": 382,
					"cross": [
						111,
						111
					]
				},
				"offset": {
					"dx": 362,
					"dy": -3
				},
				"warps": 1
			},
			{
				"dir": "W",
				"map": "gef_fild09",
				"dst": {
					"x": 368,
					"y": 92
				},
				"edge": {
					"axis": "x",
					"at": 16,
					"cross": [
						102,
						102
					]
				},
				"offset": {
					"dx": -352,
					"dy": 10
				},
				"warps": 1
			},
			{
				"dir": "S",
				"map": "gef_fild03",
				"dst": {
					"x": 66,
					"y": 379
				},
				"edge": {
					"axis": "y",
					"at": 17,
					"cross": [
						69,
						69
					]
				},
				"offset": {
					"dx": 3,
					"dy": -362
				},
				"warps": 1
			}
		]
	},
	"gef_fild02": {
		"neighbors": [
			{
				"dir": "E",
				"map": "prt_fild07",
				"dst": {
					"x": 21,
					"y": 143
				},
				"edge": {
					"axis": "x",
					"at": 380,
					"cross": [
						68,
						289
					]
				},
				"offset": {
					"dx": 359,
					"dy": 13
				},
				"warps": 3
			},
			{
				"dir": "S",
				"map": "prt_fild10",
				"dst": {
					"x": 227,
					"y": 296
				},
				"edge": {
					"axis": "y",
					"at": 18,
					"cross": [
						266,
						266
					]
				},
				"offset": {
					"dx": 39,
					"dy": -278
				},
				"warps": 1
			},
			{
				"dir": "W",
				"map": "gef_fild03",
				"dst": {
					"x": 379,
					"y": 77
				},
				"edge": {
					"axis": "x",
					"at": 14,
					"cross": [
						78,
						275
					]
				},
				"offset": {
					"dx": -365,
					"dy": 1
				},
				"warps": 2
			}
		]
	},
	"gef_fild03": {
		"neighbors": [
			{
				"dir": "S",
				"map": "prt_fild11",
				"dst": {
					"x": 302,
					"y": 298
				},
				"edge": {
					"axis": "y",
					"at": 16,
					"cross": [
						312,
						312
					]
				},
				"offset": {
					"dx": 10,
					"dy": -282
				},
				"warps": 1
			},
			{
				"dir": "N",
				"map": "gef_fild01",
				"dst": {
					"x": 69,
					"y": 20
				},
				"edge": {
					"axis": "y",
					"at": 382,
					"cross": [
						66,
						66
					]
				},
				"offset": {
					"dx": -3,
					"dy": 362
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "gef_fild02",
				"dst": {
					"x": 17,
					"y": 78
				},
				"edge": {
					"axis": "x",
					"at": 382,
					"cross": [
						77,
						277
					]
				},
				"offset": {
					"dx": 365,
					"dy": -1
				},
				"warps": 2
			},
			{
				"dir": "W",
				"map": "gef_fild10",
				"dst": {
					"x": 367,
					"y": 56
				},
				"edge": {
					"axis": "x",
					"at": 18,
					"cross": [
						52,
						52
					]
				},
				"offset": {
					"dx": -349,
					"dy": -4
				},
				"warps": 1
			}
		]
	},
	"gef_fild04": {
		"neighbors": [
			{
				"dir": "N",
				"map": "mjolnir_01",
				"dst": {
					"x": 284,
					"y": 21
				},
				"edge": {
					"axis": "y",
					"at": 362,
					"cross": [
						261,
						261
					]
				},
				"offset": {
					"dx": -23,
					"dy": 341
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "mjolnir_06",
				"dst": {
					"x": 21,
					"y": 331
				},
				"edge": {
					"axis": "x",
					"at": 362,
					"cross": [
						322,
						322
					]
				},
				"offset": {
					"dx": 341,
					"dy": -9
				},
				"warps": 1
			},
			{
				"dir": "W",
				"map": "gef_fild05",
				"dst": {
					"x": 361,
					"y": 309
				},
				"edge": {
					"axis": "x",
					"at": 16,
					"cross": [
						309,
						309
					]
				},
				"offset": {
					"dx": -345,
					"dy": 0
				},
				"warps": 1
			}
		]
	},
	"gef_fild05": {
		"neighbors": [
			{
				"dir": "E",
				"map": "gef_fild04",
				"dst": {
					"x": 19,
					"y": 309
				},
				"edge": {
					"axis": "x",
					"at": 364,
					"cross": [
						309,
						309
					]
				},
				"offset": {
					"dx": 345,
					"dy": 0
				},
				"warps": 1
			},
			{
				"dir": "W",
				"map": "gef_fild06",
				"dst": {
					"x": 379,
					"y": 211
				},
				"edge": {
					"axis": "x",
					"at": 15,
					"cross": [
						201,
						201
					]
				},
				"offset": {
					"dx": -364,
					"dy": -10
				},
				"warps": 1
			},
			{
				"dir": "S",
				"map": "gef_fild07",
				"dst": {
					"x": 64,
					"y": 360
				},
				"edge": {
					"axis": "y",
					"at": 15,
					"cross": [
						64,
						64
					]
				},
				"offset": {
					"dx": 0,
					"dy": -345
				},
				"warps": 1
			}
		]
	},
	"gef_fild06": {
		"neighbors": [
			{
				"dir": "E",
				"map": "gef_fild05",
				"dst": {
					"x": 18,
					"y": 201
				},
				"edge": {
					"axis": "x",
					"at": 382,
					"cross": [
						211,
						211
					]
				},
				"offset": {
					"dx": 364,
					"dy": 10
				},
				"warps": 1
			},
			{
				"dir": "S",
				"map": "gef_fild08",
				"dst": {
					"x": 200,
					"y": 352
				},
				"edge": {
					"axis": "y",
					"at": 17,
					"cross": [
						218,
						218
					]
				},
				"offset": {
					"dx": 18,
					"dy": -335
				},
				"warps": 1
			}
		]
	},
	"gef_fild07": {
		"neighbors": [
			{
				"dir": "N",
				"map": "gef_fild05",
				"dst": {
					"x": 64,
					"y": 18
				},
				"edge": {
					"axis": "y",
					"at": 363,
					"cross": [
						64,
						64
					]
				},
				"offset": {
					"dx": 0,
					"dy": 345
				},
				"warps": 1
			},
			{
				"dir": "W",
				"map": "gef_fild08",
				"dst": {
					"x": 357,
					"y": 187
				},
				"edge": {
					"axis": "x",
					"at": 18,
					"cross": [
						191,
						191
					]
				},
				"offset": {
					"dx": -339,
					"dy": 4
				},
				"warps": 1
			},
			{
				"dir": "S",
				"map": "gef_fild13",
				"dst": {
					"x": 41,
					"y": 369
				},
				"edge": {
					"axis": "y",
					"at": 19,
					"cross": [
						40,
						40
					]
				},
				"offset": {
					"dx": -1,
					"dy": -350
				},
				"warps": 1
			}
		]
	},
	"gef_fild08": {
		"neighbors": [
			{
				"dir": "N",
				"map": "gef_fild06",
				"dst": {
					"x": 218,
					"y": 20
				},
				"edge": {
					"axis": "y",
					"at": 355,
					"cross": [
						200,
						200
					]
				},
				"offset": {
					"dx": -18,
					"dy": 335
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "gef_fild07",
				"dst": {
					"x": 21,
					"y": 191
				},
				"edge": {
					"axis": "x",
					"at": 360,
					"cross": [
						187,
						187
					]
				},
				"offset": {
					"dx": 339,
					"dy": -4
				},
				"warps": 1
			}
		]
	},
	"gef_fild09": {
		"neighbors": [
			{
				"dir": "W",
				"map": "gef_fild13",
				"dst": {
					"x": 376,
					"y": 56
				},
				"edge": {
					"axis": "x",
					"at": 23,
					"cross": [
						56,
						56
					]
				},
				"offset": {
					"dx": -353,
					"dy": 0
				},
				"warps": 1
			},
			{
				"dir": "S",
				"map": "gef_fild10",
				"dst": {
					"x": 251,
					"y": 368
				},
				"edge": {
					"axis": "y",
					"at": 25,
					"cross": [
						225,
						225
					]
				},
				"offset": {
					"dx": -26,
					"dy": -343
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "gef_fild01",
				"dst": {
					"x": 19,
					"y": 102
				},
				"edge": {
					"axis": "x",
					"at": 368,
					"cross": [
						95,
						95
					]
				},
				"offset": {
					"dx": 349,
					"dy": -7
				},
				"warps": 1
			}
		]
	},
	"gef_fild10": {
		"neighbors": [
			{
				"dir": "N",
				"map": "gef_fild09",
				"dst": {
					"x": 225,
					"y": 28
				},
				"edge": {
					"axis": "y",
					"at": 371,
					"cross": [
						251,
						251
					]
				},
				"offset": {
					"dx": 26,
					"dy": 343
				},
				"warps": 1
			},
			{
				"dir": "S",
				"map": "gef_fild11",
				"dst": {
					"x": 114,
					"y": 360
				},
				"edge": {
					"axis": "y",
					"at": 21,
					"cross": [
						104,
						104
					]
				},
				"offset": {
					"dx": -10,
					"dy": -339
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "gef_fild03",
				"dst": {
					"x": 21,
					"y": 52
				},
				"edge": {
					"axis": "x",
					"at": 370,
					"cross": [
						56,
						56
					]
				},
				"offset": {
					"dx": 349,
					"dy": 4
				},
				"warps": 1
			}
		]
	},
	"gef_fild11": {
		"neighbors": [
			{
				"dir": "E",
				"map": "prt_fild11",
				"dst": {
					"x": 20,
					"y": 281
				},
				"edge": {
					"axis": "x",
					"at": 377,
					"cross": [
						293,
						293
					]
				},
				"offset": {
					"dx": 357,
					"dy": 12
				},
				"warps": 1
			},
			{
				"dir": "N",
				"map": "gef_fild10",
				"dst": {
					"x": 104,
					"y": 24
				},
				"edge": {
					"axis": "y",
					"at": 364,
					"cross": [
						111,
						111
					]
				},
				"offset": {
					"dx": 7,
					"dy": 340
				},
				"warps": 1
			}
		]
	},
	"gef_fild13": {
		"neighbors": [
			{
				"dir": "E",
				"map": "gef_fild09",
				"dst": {
					"x": 27,
					"y": 56
				},
				"edge": {
					"axis": "x",
					"at": 380,
					"cross": [
						56,
						56
					]
				},
				"offset": {
					"dx": 353,
					"dy": 0
				},
				"warps": 1
			},
			{
				"dir": "N",
				"map": "gef_fild07",
				"dst": {
					"x": 40,
					"y": 23
				},
				"edge": {
					"axis": "y",
					"at": 373,
					"cross": [
						41,
						41
					]
				},
				"offset": {
					"dx": 1,
					"dy": 350
				},
				"warps": 1
			}
		]
	},
	"gw_fild01": {
		"neighbors": [
			{
				"dir": "S",
				"map": "gw_fild02",
				"dst": {
					"x": 122,
					"y": 385
				},
				"edge": {
					"axis": "y",
					"at": 9,
					"cross": [
						135,
						135
					]
				},
				"offset": {
					"dx": 13,
					"dy": -376
				},
				"warps": 1
			}
		]
	},
	"gw_fild02": {
		"neighbors": [
			{
				"dir": "N",
				"map": "gw_fild01",
				"dst": {
					"x": 135,
					"y": 14
				},
				"edge": {
					"axis": "y",
					"at": 391,
					"cross": [
						122,
						122
					]
				},
				"offset": {
					"dx": -13,
					"dy": 377
				},
				"warps": 1
			}
		]
	},
	"hu_fild01": {
		"neighbors": [
			{
				"dir": "E",
				"map": "hu_fild02",
				"dst": {
					"x": 22,
					"y": 168
				},
				"edge": {
					"axis": "x",
					"at": 366,
					"cross": [
						185,
						185
					]
				},
				"offset": {
					"dx": 344,
					"dy": 17
				},
				"warps": 1
			},
			{
				"dir": "S",
				"map": "yuno_fild06",
				"dst": {
					"x": 156,
					"y": 368
				},
				"edge": {
					"axis": "y",
					"at": 36,
					"cross": [
						141,
						141
					]
				},
				"offset": {
					"dx": -15,
					"dy": -332
				},
				"warps": 1
			}
		]
	},
	"hu_fild02": {
		"neighbors": [
			{
				"dir": "W",
				"map": "hu_fild01",
				"dst": {
					"x": 361,
					"y": 189
				},
				"edge": {
					"axis": "x",
					"at": 17,
					"cross": [
						168,
						168
					]
				},
				"offset": {
					"dx": -344,
					"dy": -21
				},
				"warps": 1
			},
			{
				"dir": "S",
				"map": "hu_fild04",
				"dst": {
					"x": 48,
					"y": 368
				},
				"edge": {
					"axis": "y",
					"at": 22,
					"cross": [
						40,
						283
					]
				},
				"offset": {
					"dx": -8,
					"dy": -346
				},
				"warps": 2
			}
		]
	},
	"hu_fild04": {
		"neighbors": [
			{
				"dir": "N",
				"map": "hu_fild02",
				"dst": {
					"x": 40,
					"y": 27
				},
				"edge": {
					"axis": "y",
					"at": 372,
					"cross": [
						47,
						294
					]
				},
				"offset": {
					"dx": 7,
					"dy": 345
				},
				"warps": 2
			},
			{
				"dir": "W",
				"map": "yuno_fild06",
				"dst": {
					"x": 362,
					"y": 132
				},
				"edge": {
					"axis": "x",
					"at": 27,
					"cross": [
						126,
						126
					]
				},
				"offset": {
					"dx": -335,
					"dy": -6
				},
				"warps": 1
			},
			{
				"dir": "S",
				"map": "yuno_fild02",
				"dst": {
					"x": 114,
					"y": 370
				},
				"edge": {
					"axis": "y",
					"at": 27,
					"cross": [
						122,
						122
					]
				},
				"offset": {
					"dx": 8,
					"dy": -343
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "hu_fild05",
				"dst": {
					"x": 39,
					"y": 206
				},
				"edge": {
					"axis": "x",
					"at": 380,
					"cross": [
						183,
						183
					]
				},
				"offset": {
					"dx": 341,
					"dy": -23
				},
				"warps": 1
			}
		]
	},
	"hu_fild05": {
		"neighbors": [
			{
				"dir": "E",
				"map": "hu_fild06",
				"dst": {
					"x": 34,
					"y": 119
				},
				"edge": {
					"axis": "x",
					"at": 353,
					"cross": [
						126,
						126
					]
				},
				"offset": {
					"dx": 319,
					"dy": 7
				},
				"warps": 1
			},
			{
				"dir": "W",
				"map": "hu_fild04",
				"dst": {
					"x": 373,
					"y": 181
				},
				"edge": {
					"axis": "x",
					"at": 33,
					"cross": [
						198,
						198
					]
				},
				"offset": {
					"dx": -340,
					"dy": 17
				},
				"warps": 1
			}
		]
	},
	"hu_fild06": {
		"neighbors": [
			{
				"dir": "W",
				"map": "hu_fild05",
				"dst": {
					"x": 347,
					"y": 130
				},
				"edge": {
					"axis": "x",
					"at": 28,
					"cross": [
						119,
						119
					]
				},
				"offset": {
					"dx": -319,
					"dy": -11
				},
				"warps": 1
			}
		]
	},
	"lhz_fild01": {
		"neighbors": [
			{
				"dir": "N",
				"map": "ra_fild06",
				"dst": {
					"x": 298,
					"y": 25
				},
				"edge": {
					"axis": "y",
					"at": 382,
					"cross": [
						296,
						296
					]
				},
				"offset": {
					"dx": -2,
					"dy": 357
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "lhz_fild02",
				"dst": {
					"x": 36,
					"y": 221
				},
				"edge": {
					"axis": "x",
					"at": 367,
					"cross": [
						222,
						222
					]
				},
				"offset": {
					"dx": 331,
					"dy": 1
				},
				"warps": 1
			}
		]
	},
	"lhz_fild02": {
		"neighbors": [
			{
				"dir": "N",
				"map": "ein_fild03",
				"dst": {
					"x": 142,
					"y": 34
				},
				"edge": {
					"axis": "y",
					"at": 367,
					"cross": [
						166,
						166
					]
				},
				"offset": {
					"dx": 24,
					"dy": 333
				},
				"warps": 1
			},
			{
				"dir": "S",
				"map": "lhz_fild03",
				"dst": {
					"x": 158,
					"y": 347
				},
				"edge": {
					"axis": "y",
					"at": 37,
					"cross": [
						164,
						164
					]
				},
				"offset": {
					"dx": 6,
					"dy": -310
				},
				"warps": 1
			},
			{
				"dir": "W",
				"map": "lhz_fild01",
				"dst": {
					"x": 361,
					"y": 222
				},
				"edge": {
					"axis": "x",
					"at": 29,
					"cross": [
						219,
						219
					]
				},
				"offset": {
					"dx": -332,
					"dy": -3
				},
				"warps": 1
			}
		]
	},
	"lhz_fild03": {
		"neighbors": [
			{
				"dir": "N",
				"map": "lhz_fild02",
				"dst": {
					"x": 164,
					"y": 39
				},
				"edge": {
					"axis": "y",
					"at": 349,
					"cross": [
						158,
						158
					]
				},
				"offset": {
					"dx": -6,
					"dy": 310
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "ein_fild08",
				"dst": {
					"x": 25,
					"y": 275
				},
				"edge": {
					"axis": "x",
					"at": 363,
					"cross": [
						283,
						283
					]
				},
				"offset": {
					"dx": 338,
					"dy": 8
				},
				"warps": 1
			}
		]
	},
	"man_fild01": {
		"neighbors": [
			{
				"dir": "S",
				"map": "man_fild03",
				"dst": {
					"x": 84,
					"y": 366
				},
				"edge": {
					"axis": "y",
					"at": 55,
					"cross": [
						103,
						103
					]
				},
				"offset": {
					"dx": 19,
					"dy": -311
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "man_fild02",
				"dst": {
					"x": 34,
					"y": 261
				},
				"edge": {
					"axis": "x",
					"at": 372,
					"cross": [
						230,
						230
					]
				},
				"offset": {
					"dx": 338,
					"dy": -31
				},
				"warps": 1
			}
		]
	},
	"man_fild02": {
		"neighbors": [
			{
				"dir": "W",
				"map": "man_fild01",
				"dst": {
					"x": 369,
					"y": 230
				},
				"edge": {
					"axis": "x",
					"at": 32,
					"cross": [
						261,
						261
					]
				},
				"offset": {
					"dx": -337,
					"dy": 31
				},
				"warps": 1
			}
		]
	},
	"man_fild03": {
		"neighbors": [
			{
				"dir": "N",
				"map": "man_fild01",
				"dst": {
					"x": 103,
					"y": 58
				},
				"edge": {
					"axis": "y",
					"at": 369,
					"cross": [
						84,
						84
					]
				},
				"offset": {
					"dx": -19,
					"dy": 311
				},
				"warps": 1
			}
		]
	},
	"mjolnir_01": {
		"neighbors": [
			{
				"dir": "S",
				"map": "gef_fild04",
				"dst": {
					"x": 261,
					"y": 359
				},
				"edge": {
					"axis": "y",
					"at": 18,
					"cross": [
						284,
						284
					]
				},
				"offset": {
					"dx": 23,
					"dy": -341
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "mjolnir_02",
				"dst": {
					"x": 31,
					"y": 258
				},
				"edge": {
					"axis": "x",
					"at": 378,
					"cross": [
						256,
						256
					]
				},
				"offset": {
					"dx": 347,
					"dy": -2
				},
				"warps": 1
			}
		]
	},
	"mjolnir_02": {
		"neighbors": [
			{
				"dir": "W",
				"map": "mjolnir_01",
				"dst": {
					"x": 374,
					"y": 256
				},
				"edge": {
					"axis": "x",
					"at": 28,
					"cross": [
						258,
						258
					]
				},
				"offset": {
					"dx": -346,
					"dy": 2
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "mjolnir_03",
				"dst": {
					"x": 24,
					"y": 258
				},
				"edge": {
					"axis": "x",
					"at": 326,
					"cross": [
						289,
						289
					]
				},
				"offset": {
					"dx": 302,
					"dy": 31
				},
				"warps": 1
			},
			{
				"dir": "S",
				"map": "mjolnir_06",
				"dst": {
					"x": 366,
					"y": 380
				},
				"edge": {
					"axis": "y",
					"at": 18,
					"cross": [
						361,
						361
					]
				},
				"offset": {
					"dx": -5,
					"dy": -362
				},
				"warps": 1
			}
		]
	},
	"mjolnir_03": {
		"neighbors": [
			{
				"dir": "W",
				"map": "mjolnir_02",
				"dst": {
					"x": 323,
					"y": 289
				},
				"edge": {
					"axis": "x",
					"at": 21,
					"cross": [
						258,
						258
					]
				},
				"offset": {
					"dx": -302,
					"dy": -31
				},
				"warps": 1
			},
			{
				"dir": "S",
				"map": "mjolnir_07",
				"dst": {
					"x": 214,
					"y": 380
				},
				"edge": {
					"axis": "y",
					"at": 17,
					"cross": [
						212,
						212
					]
				},
				"offset": {
					"dx": -2,
					"dy": -363
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "mjolnir_04",
				"dst": {
					"x": 125,
					"y": 208
				},
				"edge": {
					"axis": "x",
					"at": 242,
					"cross": [
						204,
						204
					]
				},
				"offset": {
					"dx": 117,
					"dy": -4
				},
				"warps": 1
			}
		]
	},
	"mjolnir_04": {
		"neighbors": [
			{
				"dir": "W",
				"map": "mjolnir_03",
				"dst": {
					"x": 239,
					"y": 204
				},
				"edge": {
					"axis": "x",
					"at": 122,
					"cross": [
						208,
						208
					]
				},
				"offset": {
					"dx": -117,
					"dy": 4
				},
				"warps": 1
			},
			{
				"dir": "S",
				"map": "mjolnir_08",
				"dst": {
					"x": 159,
					"y": 370
				},
				"edge": {
					"axis": "y",
					"at": 46,
					"cross": [
						160,
						160
					]
				},
				"offset": {
					"dx": 1,
					"dy": -324
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "mjolnir_05",
				"dst": {
					"x": 19,
					"y": 171
				},
				"edge": {
					"axis": "x",
					"at": 387,
					"cross": [
						174,
						174
					]
				},
				"offset": {
					"dx": 368,
					"dy": 3
				},
				"warps": 1
			}
		]
	},
	"mjolnir_05": {
		"neighbors": [
			{
				"dir": "W",
				"map": "mjolnir_04",
				"dst": {
					"x": 384,
					"y": 174
				},
				"edge": {
					"axis": "x",
					"at": 16,
					"cross": [
						171,
						171
					]
				},
				"offset": {
					"dx": -368,
					"dy": -3
				},
				"warps": 1
			},
			{
				"dir": "N",
				"map": "mjolnir_12",
				"dst": {
					"x": 220,
					"y": 29
				},
				"edge": {
					"axis": "y",
					"at": 382,
					"cross": [
						220,
						220
					]
				},
				"offset": {
					"dx": 0,
					"dy": 353
				},
				"warps": 1
			},
			{
				"dir": "S",
				"map": "mjolnir_10",
				"dst": {
					"x": 235,
					"y": 378
				},
				"edge": {
					"axis": "y",
					"at": 16,
					"cross": [
						235,
						235
					]
				},
				"offset": {
					"dx": 0,
					"dy": -362
				},
				"warps": 1
			}
		]
	},
	"mjolnir_06": {
		"neighbors": [
			{
				"dir": "W",
				"map": "gef_fild04",
				"dst": {
					"x": 359,
					"y": 322
				},
				"edge": {
					"axis": "x",
					"at": 18,
					"cross": [
						331,
						331
					]
				},
				"offset": {
					"dx": -341,
					"dy": 9
				},
				"warps": 1
			},
			{
				"dir": "S",
				"map": "gef_fild00",
				"dst": {
					"x": 267,
					"y": 379
				},
				"edge": {
					"axis": "y",
					"at": 29,
					"cross": [
						265,
						265
					]
				},
				"offset": {
					"dx": -2,
					"dy": -350
				},
				"warps": 1
			},
			{
				"dir": "N",
				"map": "mjolnir_02",
				"dst": {
					"x": 361,
					"y": 21
				},
				"edge": {
					"axis": "y",
					"at": 383,
					"cross": [
						366,
						366
					]
				},
				"offset": {
					"dx": 5,
					"dy": 362
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "mjolnir_07",
				"dst": {
					"x": 19,
					"y": 377
				},
				"edge": {
					"axis": "x",
					"at": 382,
					"cross": [
						74,
						377
					]
				},
				"offset": {
					"dx": 363,
					"dy": 0
				},
				"warps": 2
			}
		]
	},
	"mjolnir_07": {
		"neighbors": [
			{
				"dir": "S",
				"map": "prt_fild00",
				"dst": {
					"x": 159,
					"y": 380
				},
				"edge": {
					"axis": "y",
					"at": 16,
					"cross": [
						156,
						156
					]
				},
				"offset": {
					"dx": -3,
					"dy": -364
				},
				"warps": 1
			},
			{
				"dir": "W",
				"map": "mjolnir_06",
				"dst": {
					"x": 379,
					"y": 377
				},
				"edge": {
					"axis": "x",
					"at": 16,
					"cross": [
						77,
						377
					]
				},
				"offset": {
					"dx": -363,
					"dy": 0
				},
				"warps": 2
			},
			{
				"dir": "N",
				"map": "mjolnir_03",
				"dst": {
					"x": 212,
					"y": 20
				},
				"edge": {
					"axis": "y",
					"at": 383,
					"cross": [
						214,
						214
					]
				},
				"offset": {
					"dx": 2,
					"dy": 363
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "mjolnir_08",
				"dst": {
					"x": 33,
					"y": 234
				},
				"edge": {
					"axis": "x",
					"at": 383,
					"cross": [
						233,
						362
					]
				},
				"offset": {
					"dx": 350,
					"dy": -1
				},
				"warps": 2
			}
		]
	},
	"mjolnir_08": {
		"neighbors": [
			{
				"dir": "N",
				"map": "mjolnir_04",
				"dst": {
					"x": 160,
					"y": 49
				},
				"edge": {
					"axis": "y",
					"at": 373,
					"cross": [
						159,
						159
					]
				},
				"offset": {
					"dx": -1,
					"dy": 324
				},
				"warps": 1
			},
			{
				"dir": "S",
				"map": "mjolnir_09",
				"dst": {
					"x": 196,
					"y": 364
				},
				"edge": {
					"axis": "y",
					"at": 28,
					"cross": [
						185,
						185
					]
				},
				"offset": {
					"dx": -11,
					"dy": -336
				},
				"warps": 1
			},
			{
				"dir": "W",
				"map": "mjolnir_07",
				"dst": {
					"x": 380,
					"y": 362
				},
				"edge": {
					"axis": "x",
					"at": 29,
					"cross": [
						234,
						346
					]
				},
				"offset": {
					"dx": -351,
					"dy": -16
				},
				"warps": 2
			},
			{
				"dir": "E",
				"map": "mjolnir_10",
				"dst": {
					"x": 18,
					"y": 258
				},
				"edge": {
					"axis": "x",
					"at": 369,
					"cross": [
						257,
						257
					]
				},
				"offset": {
					"dx": 351,
					"dy": -1
				},
				"warps": 1
			}
		]
	},
	"mjolnir_09": {
		"neighbors": [
			{
				"dir": "S",
				"map": "prt_fild05",
				"dst": {
					"x": 105,
					"y": 378
				},
				"edge": {
					"axis": "y",
					"at": 28,
					"cross": [
						106,
						300
					]
				},
				"offset": {
					"dx": 1,
					"dy": -350
				},
				"warps": 2
			},
			{
				"dir": "N",
				"map": "mjolnir_08",
				"dst": {
					"x": 185,
					"y": 31
				},
				"edge": {
					"axis": "y",
					"at": 367,
					"cross": [
						194,
						194
					]
				},
				"offset": {
					"dx": 9,
					"dy": 336
				},
				"warps": 1
			},
			{
				"dir": "W",
				"map": "prt_fild00",
				"dst": {
					"x": 380,
					"y": 249
				},
				"edge": {
					"axis": "x",
					"at": 30,
					"cross": [
						249,
						249
					]
				},
				"offset": {
					"dx": -350,
					"dy": 0
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "prt_fild01",
				"dst": {
					"x": 23,
					"y": 292
				},
				"edge": {
					"axis": "x",
					"at": 373,
					"cross": [
						288,
						288
					]
				},
				"offset": {
					"dx": 350,
					"dy": -4
				},
				"warps": 1
			}
		]
	},
	"mjolnir_10": {
		"neighbors": [
			{
				"dir": "W",
				"map": "mjolnir_08",
				"dst": {
					"x": 366,
					"y": 257
				},
				"edge": {
					"axis": "x",
					"at": 15,
					"cross": [
						258,
						258
					]
				},
				"offset": {
					"dx": -351,
					"dy": 1
				},
				"warps": 1
			},
			{
				"dir": "N",
				"map": "mjolnir_05",
				"dst": {
					"x": 235,
					"y": 19
				},
				"edge": {
					"axis": "y",
					"at": 381,
					"cross": [
						235,
						235
					]
				},
				"offset": {
					"dx": 0,
					"dy": 362
				},
				"warps": 1
			},
			{
				"dir": "S",
				"map": "prt_fild01",
				"dst": {
					"x": 261,
					"y": 370
				},
				"edge": {
					"axis": "y",
					"at": 13,
					"cross": [
						66,
						265
					]
				},
				"offset": {
					"dx": 4,
					"dy": -357
				},
				"warps": 2
			},
			{
				"dir": "E",
				"map": "mjolnir_11",
				"dst": {
					"x": 23,
					"y": 220
				},
				"edge": {
					"axis": "x",
					"at": 384,
					"cross": [
						220,
						220
					]
				},
				"offset": {
					"dx": 361,
					"dy": 0
				},
				"warps": 1
			}
		]
	},
	"mjolnir_11": {
		"neighbors": [
			{
				"dir": "S",
				"map": "prt_fild02",
				"dst": {
					"x": 173,
					"y": 379
				},
				"edge": {
					"axis": "y",
					"at": 20,
					"cross": [
						174,
						174
					]
				},
				"offset": {
					"dx": 1,
					"dy": -359
				},
				"warps": 1
			},
			{
				"dir": "W",
				"map": "mjolnir_10",
				"dst": {
					"x": 381,
					"y": 220
				},
				"edge": {
					"axis": "x",
					"at": 20,
					"cross": [
						220,
						220
					]
				},
				"offset": {
					"dx": -361,
					"dy": 0
				},
				"warps": 1
			}
		]
	},
	"mjolnir_12": {
		"neighbors": [
			{
				"dir": "S",
				"map": "mjolnir_05",
				"dst": {
					"x": 220,
					"y": 379
				},
				"edge": {
					"axis": "y",
					"at": 26,
					"cross": [
						220,
						220
					]
				},
				"offset": {
					"dx": 0,
					"dy": -353
				},
				"warps": 1
			}
		]
	},
	"moc_fild01": {
		"neighbors": [
			{
				"dir": "W",
				"map": "prt_fild09",
				"dst": {
					"x": 380,
					"y": 237
				},
				"edge": {
					"axis": "x",
					"at": 22,
					"cross": [
						242,
						242
					]
				},
				"offset": {
					"dx": -358,
					"dy": 5
				},
				"warps": 1
			},
			{
				"dir": "N",
				"map": "prt_fild08",
				"dst": {
					"x": 233,
					"y": 20
				},
				"edge": {
					"axis": "y",
					"at": 382,
					"cross": [
						56,
						239
					]
				},
				"offset": {
					"dx": 6,
					"dy": 362
				},
				"warps": 2
			},
			{
				"dir": "S",
				"map": "moc_fild02",
				"dst": {
					"x": 77,
					"y": 338
				},
				"edge": {
					"axis": "y",
					"at": 16,
					"cross": [
						301,
						341
					]
				},
				"offset": {
					"dx": 224,
					"dy": -322
				},
				"warps": 3
			},
			{
				"dir": "E",
				"map": "pay_fild04",
				"dst": {
					"x": 20,
					"y": 165
				},
				"edge": {
					"axis": "x",
					"at": 379,
					"cross": [
						162,
						162
					]
				},
				"offset": {
					"dx": 359,
					"dy": -3
				},
				"warps": 1
			}
		]
	},
	"moc_fild02": {
		"neighbors": [
			{
				"dir": "S",
				"map": "moc_fild13",
				"dst": {
					"x": 298,
					"y": 367
				},
				"edge": {
					"axis": "y",
					"at": 29,
					"cross": [
						71,
						228
					]
				},
				"offset": {
					"dx": -70,
					"dy": -338
				},
				"warps": 2
			},
			{
				"dir": "S",
				"map": "moc_fild03",
				"dst": {
					"x": 70,
					"y": 336
				},
				"edge": {
					"axis": "y",
					"at": 19,
					"cross": [
						332,
						332
					]
				},
				"offset": {
					"dx": 262,
					"dy": -317
				},
				"warps": 1
			},
			{
				"dir": "N",
				"map": "pay_fild04",
				"dst": {
					"x": 194,
					"y": 20
				},
				"edge": {
					"axis": "y",
					"at": 339,
					"cross": [
						350,
						350
					]
				},
				"offset": {
					"dx": 156,
					"dy": 319
				},
				"warps": 1
			},
			{
				"dir": "N",
				"map": "moc_fild01",
				"dst": {
					"x": 315,
					"y": 25
				},
				"edge": {
					"axis": "y",
					"at": 342,
					"cross": [
						67,
						92
					]
				},
				"offset": {
					"dx": -248,
					"dy": 317
				},
				"warps": 2
			}
		]
	},
	"moc_fild03": {
		"neighbors": [
			{
				"dir": "W",
				"map": "moc_fild13",
				"dst": {
					"x": 305,
					"y": 49
				},
				"edge": {
					"axis": "x",
					"at": 17,
					"cross": [
						37,
						37
					]
				},
				"offset": {
					"dx": -288,
					"dy": -12
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "pay_fild01",
				"dst": {
					"x": 17,
					"y": 152
				},
				"edge": {
					"axis": "x",
					"at": 303,
					"cross": [
						170,
						170
					]
				},
				"offset": {
					"dx": 286,
					"dy": 18
				},
				"warps": 1
			},
			{
				"dir": "N",
				"map": "moc_fild02",
				"dst": {
					"x": 332,
					"y": 23
				},
				"edge": {
					"axis": "y",
					"at": 341,
					"cross": [
						70,
						70
					]
				},
				"offset": {
					"dx": -262,
					"dy": 318
				},
				"warps": 1
			}
		]
	},
	"moc_fild11": {
		"neighbors": [
			{
				"dir": "S",
				"map": "moc_fild17",
				"dst": {
					"x": 218,
					"y": 366
				},
				"edge": {
					"axis": "y",
					"at": 29,
					"cross": [
						212,
						212
					]
				},
				"offset": {
					"dx": -6,
					"dy": -337
				},
				"warps": 1
			},
			{
				"dir": "W",
				"map": "moc_fild12",
				"dst": {
					"x": 286,
					"y": 168
				},
				"edge": {
					"axis": "x",
					"at": 26,
					"cross": [
						161,
						161
					]
				},
				"offset": {
					"dx": -260,
					"dy": -7
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "moc_fild20",
				"dst": {
					"x": 36,
					"y": 177
				},
				"edge": {
					"axis": "x",
					"at": 377,
					"cross": [
						197,
						197
					]
				},
				"offset": {
					"dx": 341,
					"dy": 20
				},
				"warps": 1
			}
		]
	},
	"moc_fild12": {
		"neighbors": [
			{
				"dir": "S",
				"map": "moc_fild18",
				"dst": {
					"x": 158,
					"y": 379
				},
				"edge": {
					"axis": "y",
					"at": 30,
					"cross": [
						118,
						118
					]
				},
				"offset": {
					"dx": -40,
					"dy": -349
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "moc_fild11",
				"dst": {
					"x": 29,
					"y": 161
				},
				"edge": {
					"axis": "x",
					"at": 289,
					"cross": [
						168,
						168
					]
				},
				"offset": {
					"dx": 260,
					"dy": 7
				},
				"warps": 1
			}
		]
	},
	"moc_fild13": {
		"neighbors": [
			{
				"dir": "N",
				"map": "moc_fild02",
				"dst": {
					"x": 71,
					"y": 21
				},
				"edge": {
					"axis": "y",
					"at": 368,
					"cross": [
						146,
						298
					]
				},
				"offset": {
					"dx": 75,
					"dy": 347
				},
				"warps": 2
			},
			{
				"dir": "E",
				"map": "moc_fild03",
				"dst": {
					"x": 20,
					"y": 37
				},
				"edge": {
					"axis": "x",
					"at": 308,
					"cross": [
						49,
						49
					]
				},
				"offset": {
					"dx": 288,
					"dy": 12
				},
				"warps": 1
			}
		]
	},
	"moc_fild16": {
		"neighbors": [
			{
				"dir": "W",
				"map": "moc_fild17",
				"dst": {
					"x": 366,
					"y": 272
				},
				"edge": {
					"axis": "x",
					"at": 16,
					"cross": [
						179,
						179
					]
				},
				"offset": {
					"dx": -350,
					"dy": -93
				},
				"warps": 1
			}
		]
	},
	"moc_fild17": {
		"neighbors": [
			{
				"dir": "N",
				"map": "moc_fild11",
				"dst": {
					"x": 212,
					"y": 32
				},
				"edge": {
					"axis": "y",
					"at": 369,
					"cross": [
						218,
						218
					]
				},
				"offset": {
					"dx": 6,
					"dy": 337
				},
				"warps": 1
			},
			{
				"dir": "W",
				"map": "moc_fild18",
				"dst": {
					"x": 379,
					"y": 305
				},
				"edge": {
					"axis": "x",
					"at": 30,
					"cross": [
						300,
						300
					]
				},
				"offset": {
					"dx": -349,
					"dy": -5
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "moc_fild16",
				"dst": {
					"x": 19,
					"y": 179
				},
				"edge": {
					"axis": "x",
					"at": 369,
					"cross": [
						272,
						272
					]
				},
				"offset": {
					"dx": 350,
					"dy": 93
				},
				"warps": 1
			}
		]
	},
	"moc_fild18": {
		"neighbors": [
			{
				"dir": "W",
				"map": "cmd_fild09",
				"dst": {
					"x": 363,
					"y": 164
				},
				"edge": {
					"axis": "x",
					"at": 51,
					"cross": [
						170,
						170
					]
				},
				"offset": {
					"dx": -312,
					"dy": 6
				},
				"warps": 1
			},
			{
				"dir": "N",
				"map": "moc_fild12",
				"dst": {
					"x": 118,
					"y": 33
				},
				"edge": {
					"axis": "y",
					"at": 382,
					"cross": [
						158,
						158
					]
				},
				"offset": {
					"dx": 40,
					"dy": 349
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "moc_fild17",
				"dst": {
					"x": 33,
					"y": 300
				},
				"edge": {
					"axis": "x",
					"at": 382,
					"cross": [
						305,
						305
					]
				},
				"offset": {
					"dx": 349,
					"dy": 5
				},
				"warps": 1
			}
		]
	},
	"moc_fild21": {
		"neighbors": [
			{
				"dir": "W",
				"map": "moc_fild20",
				"dst": {
					"x": 349,
					"y": 179
				},
				"edge": {
					"axis": "x",
					"at": 26,
					"cross": [
						196,
						196
					]
				},
				"offset": {
					"dx": -323,
					"dy": 17
				},
				"warps": 1
			}
		]
	},
	"moc_fild22": {
		"neighbors": [
			{
				"dir": "W",
				"map": "moc_fild20",
				"dst": {
					"x": 349,
					"y": 179
				},
				"edge": {
					"axis": "x",
					"at": 32,
					"cross": [
						196,
						196
					]
				},
				"offset": {
					"dx": -317,
					"dy": 17
				},
				"warps": 1
			}
		]
	},
	"pay_fild01": {
		"neighbors": [
			{
				"dir": "W",
				"map": "moc_fild03",
				"dst": {
					"x": 299,
					"y": 170
				},
				"edge": {
					"axis": "x",
					"at": 13,
					"cross": [
						152,
						152
					]
				},
				"offset": {
					"dx": -286,
					"dy": -18
				},
				"warps": 1
			},
			{
				"dir": "S",
				"map": "pay_fild02",
				"dst": {
					"x": 83,
					"y": 382
				},
				"edge": {
					"axis": "y",
					"at": 14,
					"cross": [
						278,
						353
					]
				},
				"offset": {
					"dx": 195,
					"dy": -368
				},
				"warps": 2
			},
			{
				"dir": "E",
				"map": "pay_fild07",
				"dst": {
					"x": 23,
					"y": 207
				},
				"edge": {
					"axis": "x",
					"at": 379,
					"cross": [
						201,
						201
					]
				},
				"offset": {
					"dx": 356,
					"dy": -6
				},
				"warps": 1
			}
		]
	},
	"pay_fild02": {
		"neighbors": [
			{
				"dir": "N",
				"map": "pay_fild01",
				"dst": {
					"x": 354,
					"y": 18
				},
				"edge": {
					"axis": "y",
					"at": 390,
					"cross": [
						83,
						167
					]
				},
				"offset": {
					"dx": -187,
					"dy": 372
				},
				"warps": 2
			},
			{
				"dir": "E",
				"map": "pay_fild03",
				"dst": {
					"x": 20,
					"y": 110
				},
				"edge": {
					"axis": "x",
					"at": 284,
					"cross": [
						108,
						108
					]
				},
				"offset": {
					"dx": 264,
					"dy": -2
				},
				"warps": 1
			}
		]
	},
	"pay_fild03": {
		"neighbors": [
			{
				"dir": "W",
				"map": "pay_fild02",
				"dst": {
					"x": 280,
					"y": 108
				},
				"edge": {
					"axis": "x",
					"at": 15,
					"cross": [
						110,
						110
					]
				},
				"offset": {
					"dx": -265,
					"dy": 2
				},
				"warps": 1
			},
			{
				"dir": "N",
				"map": "pay_fild07",
				"dst": {
					"x": 167,
					"y": 20
				},
				"edge": {
					"axis": "y",
					"at": 281,
					"cross": [
						172,
						172
					]
				},
				"offset": {
					"dx": 5,
					"dy": 261
				},
				"warps": 1
			},
			{
				"dir": "S",
				"map": "pay_fild06",
				"dst": {
					"x": 305,
					"y": 372
				},
				"edge": {
					"axis": "y",
					"at": 16,
					"cross": [
						313,
						313
					]
				},
				"offset": {
					"dx": 8,
					"dy": -356
				},
				"warps": 1
			}
		]
	},
	"pay_fild04": {
		"neighbors": [
			{
				"dir": "W",
				"map": "moc_fild01",
				"dst": {
					"x": 376,
					"y": 162
				},
				"edge": {
					"axis": "x",
					"at": 17,
					"cross": [
						165,
						165
					]
				},
				"offset": {
					"dx": -359,
					"dy": 3
				},
				"warps": 1
			},
			{
				"dir": "S",
				"map": "moc_fild02",
				"dst": {
					"x": 350,
					"y": 336
				},
				"edge": {
					"axis": "y",
					"at": 17,
					"cross": [
						194,
						194
					]
				},
				"offset": {
					"dx": -156,
					"dy": -319
				},
				"warps": 1
			}
		]
	},
	"pay_fild06": {
		"neighbors": [
			{
				"dir": "N",
				"map": "pay_fild03",
				"dst": {
					"x": 313,
					"y": 19
				},
				"edge": {
					"axis": "y",
					"at": 375,
					"cross": [
						305,
						305
					]
				},
				"offset": {
					"dx": -8,
					"dy": 356
				},
				"warps": 1
			}
		]
	},
	"pay_fild07": {
		"neighbors": [
			{
				"dir": "W",
				"map": "pay_fild01",
				"dst": {
					"x": 371,
					"y": 205
				},
				"edge": {
					"axis": "x",
					"at": 16,
					"cross": [
						200,
						200
					]
				},
				"offset": {
					"dx": -355,
					"dy": -5
				},
				"warps": 1
			},
			{
				"dir": "S",
				"map": "pay_fild03",
				"dst": {
					"x": 177,
					"y": 275
				},
				"edge": {
					"axis": "y",
					"at": 17,
					"cross": [
						163,
						163
					]
				},
				"offset": {
					"dx": -14,
					"dy": -258
				},
				"warps": 1
			},
			{
				"dir": "N",
				"map": "pay_fild08",
				"dst": {
					"x": 160,
					"y": 19
				},
				"edge": {
					"axis": "y",
					"at": 382,
					"cross": [
						280,
						280
					]
				},
				"offset": {
					"dx": 120,
					"dy": 363
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "pay_fild10",
				"dst": {
					"x": 19,
					"y": 290
				},
				"edge": {
					"axis": "x",
					"at": 382,
					"cross": [
						290,
						290
					]
				},
				"offset": {
					"dx": 363,
					"dy": 0
				},
				"warps": 1
			}
		]
	},
	"pay_fild08": {
		"neighbors": [
			{
				"dir": "S",
				"map": "pay_fild07",
				"dst": {
					"x": 280,
					"y": 379
				},
				"edge": {
					"axis": "y",
					"at": 16,
					"cross": [
						160,
						160
					]
				},
				"offset": {
					"dx": -120,
					"dy": -363
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "pay_fild09",
				"dst": {
					"x": 19,
					"y": 91
				},
				"edge": {
					"axis": "x",
					"at": 262,
					"cross": [
						91,
						91
					]
				},
				"offset": {
					"dx": 243,
					"dy": 0
				},
				"warps": 1
			}
		]
	},
	"pay_fild09": {
		"neighbors": [
			{
				"dir": "S",
				"map": "pay_fild10",
				"dst": {
					"x": 112,
					"y": 379
				},
				"edge": {
					"axis": "y",
					"at": 16,
					"cross": [
						112,
						112
					]
				},
				"offset": {
					"dx": 0,
					"dy": -363
				},
				"warps": 1
			},
			{
				"dir": "W",
				"map": "pay_fild08",
				"dst": {
					"x": 259,
					"y": 91
				},
				"edge": {
					"axis": "x",
					"at": 16,
					"cross": [
						91,
						91
					]
				},
				"offset": {
					"dx": -243,
					"dy": 0
				},
				"warps": 1
			}
		]
	},
	"pay_fild10": {
		"neighbors": [
			{
				"dir": "N",
				"map": "pay_fild09",
				"dst": {
					"x": 112,
					"y": 19
				},
				"edge": {
					"axis": "y",
					"at": 382,
					"cross": [
						112,
						112
					]
				},
				"offset": {
					"dx": 0,
					"dy": 363
				},
				"warps": 1
			},
			{
				"dir": "W",
				"map": "pay_fild07",
				"dst": {
					"x": 379,
					"y": 290
				},
				"edge": {
					"axis": "x",
					"at": 16,
					"cross": [
						290,
						290
					]
				},
				"offset": {
					"dx": -363,
					"dy": 0
				},
				"warps": 1
			}
		]
	},
	"prt_fild00": {
		"neighbors": [
			{
				"dir": "N",
				"map": "mjolnir_07",
				"dst": {
					"x": 156,
					"y": 19
				},
				"edge": {
					"axis": "y",
					"at": 383,
					"cross": [
						159,
						159
					]
				},
				"offset": {
					"dx": 3,
					"dy": 364
				},
				"warps": 1
			},
			{
				"dir": "S",
				"map": "prt_fild04",
				"dst": {
					"x": 158,
					"y": 384
				},
				"edge": {
					"axis": "y",
					"at": 18,
					"cross": [
						165,
						317
					]
				},
				"offset": {
					"dx": 7,
					"dy": -366
				},
				"warps": 2
			},
			{
				"dir": "W",
				"map": "gef_fild00",
				"dst": {
					"x": 376,
					"y": 140
				},
				"edge": {
					"axis": "x",
					"at": 18,
					"cross": [
						129,
						129
					]
				},
				"offset": {
					"dx": -358,
					"dy": -11
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "mjolnir_09",
				"dst": {
					"x": 33,
					"y": 248
				},
				"edge": {
					"axis": "x",
					"at": 383,
					"cross": [
						249,
						249
					]
				},
				"offset": {
					"dx": 350,
					"dy": 1
				},
				"warps": 1
			}
		]
	},
	"prt_fild01": {
		"neighbors": [
			{
				"dir": "W",
				"map": "mjolnir_09",
				"dst": {
					"x": 370,
					"y": 288
				},
				"edge": {
					"axis": "x",
					"at": 20,
					"cross": [
						292,
						292
					]
				},
				"offset": {
					"dx": -350,
					"dy": 4
				},
				"warps": 1
			},
			{
				"dir": "N",
				"map": "mjolnir_10",
				"dst": {
					"x": 265,
					"y": 16
				},
				"edge": {
					"axis": "y",
					"at": 373,
					"cross": [
						66,
						261
					]
				},
				"offset": {
					"dx": -4,
					"dy": 357
				},
				"warps": 2
			},
			{
				"dir": "E",
				"map": "prt_fild02",
				"dst": {
					"x": 20,
					"y": 242
				},
				"edge": {
					"axis": "x",
					"at": 380,
					"cross": [
						243,
						351
					]
				},
				"offset": {
					"dx": 360,
					"dy": 1
				},
				"warps": 3
			}
		]
	},
	"prt_fild02": {
		"neighbors": [
			{
				"dir": "W",
				"map": "prt_fild01",
				"dst": {
					"x": 377,
					"y": 243
				},
				"edge": {
					"axis": "x",
					"at": 17,
					"cross": [
						242,
						350
					]
				},
				"offset": {
					"dx": -360,
					"dy": -1
				},
				"warps": 3
			},
			{
				"dir": "N",
				"map": "mjolnir_11",
				"dst": {
					"x": 174,
					"y": 23
				},
				"edge": {
					"axis": "y",
					"at": 382,
					"cross": [
						173,
						173
					]
				},
				"offset": {
					"dx": -1,
					"dy": 359
				},
				"warps": 1
			},
			{
				"dir": "S",
				"map": "prt_fild06",
				"dst": {
					"x": 277,
					"y": 315
				},
				"edge": {
					"axis": "y",
					"at": 17,
					"cross": [
						305,
						305
					]
				},
				"offset": {
					"dx": 28,
					"dy": -298
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "prt_fild03",
				"dst": {
					"x": 23,
					"y": 249
				},
				"edge": {
					"axis": "x",
					"at": 380,
					"cross": [
						347,
						347
					]
				},
				"offset": {
					"dx": 357,
					"dy": 98
				},
				"warps": 1
			}
		]
	},
	"prt_fild03": {
		"neighbors": [
			{
				"dir": "W",
				"map": "prt_fild02",
				"dst": {
					"x": 373,
					"y": 353
				},
				"edge": {
					"axis": "x",
					"at": 16,
					"cross": [
						249,
						249
					]
				},
				"offset": {
					"dx": -357,
					"dy": -104
				},
				"warps": 1
			}
		]
	},
	"prt_fild04": {
		"neighbors": [
			{
				"dir": "N",
				"map": "prt_fild00",
				"dst": {
					"x": 164,
					"y": 24
				},
				"edge": {
					"axis": "y",
					"at": 387,
					"cross": [
						160,
						323
					]
				},
				"offset": {
					"dx": -4,
					"dy": 363
				},
				"warps": 2
			},
			{
				"dir": "W",
				"map": "gef_fild01",
				"dst": {
					"x": 375,
					"y": 111
				},
				"edge": {
					"axis": "x",
					"at": 17,
					"cross": [
						114,
						114
					]
				},
				"offset": {
					"dx": -358,
					"dy": 3
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "prt_fild05",
				"dst": {
					"x": 17,
					"y": 59
				},
				"edge": {
					"axis": "x",
					"at": 378,
					"cross": [
						72,
						334
					]
				},
				"offset": {
					"dx": 361,
					"dy": 13
				},
				"warps": 3
			}
		]
	},
	"prt_fild05": {
		"neighbors": [
			{
				"dir": "N",
				"map": "mjolnir_09",
				"dst": {
					"x": 106,
					"y": 34
				},
				"edge": {
					"axis": "y",
					"at": 381,
					"cross": [
						105,
						292
					]
				},
				"offset": {
					"dx": -1,
					"dy": 347
				},
				"warps": 2
			},
			{
				"dir": "W",
				"map": "prt_fild04",
				"dst": {
					"x": 374,
					"y": 73
				},
				"edge": {
					"axis": "x",
					"at": 13,
					"cross": [
						63,
						333
					]
				},
				"offset": {
					"dx": -361,
					"dy": -10
				},
				"warps": 3
			},
			{
				"dir": "S",
				"map": "prt_fild07",
				"dst": {
					"x": 129,
					"y": 374
				},
				"edge": {
					"axis": "y",
					"at": 14,
					"cross": [
						134,
						255
					]
				},
				"offset": {
					"dx": 5,
					"dy": -360
				},
				"warps": 2
			}
		]
	},
	"prt_fild06": {
		"neighbors": [
			{
				"dir": "N",
				"map": "prt_fild02",
				"dst": {
					"x": 305,
					"y": 22
				},
				"edge": {
					"axis": "y",
					"at": 320,
					"cross": [
						277,
						277
					]
				},
				"offset": {
					"dx": -28,
					"dy": 298
				},
				"warps": 1
			}
		]
	},
	"prt_fild07": {
		"neighbors": [
			{
				"dir": "W",
				"map": "gef_fild02",
				"dst": {
					"x": 376,
					"y": 69
				},
				"edge": {
					"axis": "x",
					"at": 13,
					"cross": [
						64,
						289
					]
				},
				"offset": {
					"dx": -363,
					"dy": -5
				},
				"warps": 3
			},
			{
				"dir": "N",
				"map": "prt_fild05",
				"dst": {
					"x": 142,
					"y": 18
				},
				"edge": {
					"axis": "y",
					"at": 381,
					"cross": [
						132,
						248
					]
				},
				"offset": {
					"dx": -10,
					"dy": 363
				},
				"warps": 2
			},
			{
				"dir": "S",
				"map": "prt_fild09",
				"dst": {
					"x": 224,
					"y": 377
				},
				"edge": {
					"axis": "y",
					"at": 12,
					"cross": [
						84,
						206
					]
				},
				"offset": {
					"dx": -18,
					"dy": -365
				},
				"warps": 2
			},
			{
				"dir": "E",
				"map": "prt_fild08",
				"dst": {
					"x": 20,
					"y": 239
				},
				"edge": {
					"axis": "x",
					"at": 383,
					"cross": [
						186,
						239
					]
				},
				"offset": {
					"dx": 363,
					"dy": 0
				},
				"warps": 2
			}
		]
	},
	"prt_fild08": {
		"neighbors": [
			{
				"dir": "W",
				"map": "prt_fild07",
				"dst": {
					"x": 380,
					"y": 186
				},
				"edge": {
					"axis": "x",
					"at": 16,
					"cross": [
						187,
						239
					]
				},
				"offset": {
					"dx": -364,
					"dy": 1
				},
				"warps": 2
			},
			{
				"dir": "S",
				"map": "moc_fild01",
				"dst": {
					"x": 238,
					"y": 378
				},
				"edge": {
					"axis": "y",
					"at": 16,
					"cross": [
						55,
						233
					]
				},
				"offset": {
					"dx": -5,
					"dy": -362
				},
				"warps": 2
			}
		]
	},
	"prt_fild09": {
		"neighbors": [
			{
				"dir": "W",
				"map": "prt_fild10",
				"dst": {
					"x": 336,
					"y": 126
				},
				"edge": {
					"axis": "x",
					"at": 14,
					"cross": [
						124,
						139
					]
				},
				"offset": {
					"dx": -322,
					"dy": -2
				},
				"warps": 2
			},
			{
				"dir": "N",
				"map": "prt_fild07",
				"dst": {
					"x": 206,
					"y": 15
				},
				"edge": {
					"axis": "y",
					"at": 380,
					"cross": [
						87,
						224
					]
				},
				"offset": {
					"dx": 18,
					"dy": 365
				},
				"warps": 2
			},
			{
				"dir": "E",
				"map": "moc_fild01",
				"dst": {
					"x": 25,
					"y": 242
				},
				"edge": {
					"axis": "x",
					"at": 383,
					"cross": [
						223,
						251
					]
				},
				"offset": {
					"dx": 358,
					"dy": -19
				},
				"warps": 2
			}
		]
	},
	"prt_fild10": {
		"neighbors": [
			{
				"dir": "W",
				"map": "prt_fild11",
				"dst": {
					"x": 359,
					"y": 111
				},
				"edge": {
					"axis": "x",
					"at": 20,
					"cross": [
						122,
						196
					]
				},
				"offset": {
					"dx": -339,
					"dy": 11
				},
				"warps": 2
			},
			{
				"dir": "N",
				"map": "gef_fild02",
				"dst": {
					"x": 266,
					"y": 21
				},
				"edge": {
					"axis": "y",
					"at": 299,
					"cross": [
						227,
						227
					]
				},
				"offset": {
					"dx": -39,
					"dy": 278
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "prt_fild09",
				"dst": {
					"x": 17,
					"y": 133
				},
				"edge": {
					"axis": "x",
					"at": 339,
					"cross": [
						126,
						126
					]
				},
				"offset": {
					"dx": 322,
					"dy": -7
				},
				"warps": 1
			}
		]
	},
	"prt_fild11": {
		"neighbors": [
			{
				"dir": "W",
				"map": "gef_fild11",
				"dst": {
					"x": 374,
					"y": 293
				},
				"edge": {
					"axis": "x",
					"at": 17,
					"cross": [
						281,
						281
					]
				},
				"offset": {
					"dx": -357,
					"dy": -12
				},
				"warps": 1
			},
			{
				"dir": "N",
				"map": "gef_fild03",
				"dst": {
					"x": 312,
					"y": 19
				},
				"edge": {
					"axis": "y",
					"at": 301,
					"cross": [
						302,
						302
					]
				},
				"offset": {
					"dx": -10,
					"dy": 282
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "prt_fild10",
				"dst": {
					"x": 23,
					"y": 196
				},
				"edge": {
					"axis": "x",
					"at": 361,
					"cross": [
						111,
						184
					]
				},
				"offset": {
					"dx": 338,
					"dy": -12
				},
				"warps": 2
			}
		]
	},
	"ra_fild01": {
		"neighbors": [
			{
				"dir": "S",
				"map": "ra_fild04",
				"dst": {
					"x": 322,
					"y": 371
				},
				"edge": {
					"axis": "y",
					"at": 38,
					"cross": [
						306,
						306
					]
				},
				"offset": {
					"dx": -16,
					"dy": -333
				},
				"warps": 1
			}
		]
	},
	"ra_fild03": {
		"neighbors": [
			{
				"dir": "E",
				"map": "ra_fild04",
				"dst": {
					"x": 29,
					"y": 176
				},
				"edge": {
					"axis": "x",
					"at": 374,
					"cross": [
						168,
						168
					]
				},
				"offset": {
					"dx": 345,
					"dy": -8
				},
				"warps": 1
			}
		]
	},
	"ra_fild04": {
		"neighbors": [
			{
				"dir": "N",
				"map": "ra_fild01",
				"dst": {
					"x": 306,
					"y": 43
				},
				"edge": {
					"axis": "y",
					"at": 378,
					"cross": [
						322,
						322
					]
				},
				"offset": {
					"dx": 16,
					"dy": 335
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "ra_fild05",
				"dst": {
					"x": 39,
					"y": 353
				},
				"edge": {
					"axis": "x",
					"at": 362,
					"cross": [
						351,
						351
					]
				},
				"offset": {
					"dx": 323,
					"dy": -2
				},
				"warps": 1
			},
			{
				"dir": "S",
				"map": "ra_fild08",
				"dst": {
					"x": 287,
					"y": 365
				},
				"edge": {
					"axis": "y",
					"at": 54,
					"cross": [
						263,
						263
					]
				},
				"offset": {
					"dx": -24,
					"dy": -311
				},
				"warps": 1
			},
			{
				"dir": "W",
				"map": "ra_fild03",
				"dst": {
					"x": 370,
					"y": 172
				},
				"edge": {
					"axis": "x",
					"at": 23,
					"cross": [
						176,
						176
					]
				},
				"offset": {
					"dx": -347,
					"dy": 4
				},
				"warps": 1
			}
		]
	},
	"ra_fild05": {
		"neighbors": [
			{
				"dir": "W",
				"map": "ra_fild04",
				"dst": {
					"x": 356,
					"y": 351
				},
				"edge": {
					"axis": "x",
					"at": 33,
					"cross": [
						353,
						353
					]
				},
				"offset": {
					"dx": -323,
					"dy": 2
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "ra_fild06",
				"dst": {
					"x": 24,
					"y": 277
				},
				"edge": {
					"axis": "x",
					"at": 348,
					"cross": [
						274,
						274
					]
				},
				"offset": {
					"dx": 324,
					"dy": -3
				},
				"warps": 1
			}
		]
	},
	"ra_fild06": {
		"neighbors": [
			{
				"dir": "W",
				"map": "ra_fild05",
				"dst": {
					"x": 341,
					"y": 273
				},
				"edge": {
					"axis": "x",
					"at": 19,
					"cross": [
						277,
						277
					]
				},
				"offset": {
					"dx": -322,
					"dy": 4
				},
				"warps": 1
			},
			{
				"dir": "S",
				"map": "lhz_fild01",
				"dst": {
					"x": 296,
					"y": 376
				},
				"edge": {
					"axis": "y",
					"at": 21,
					"cross": [
						294,
						294
					]
				},
				"offset": {
					"dx": -2,
					"dy": -355
				},
				"warps": 1
			}
		]
	},
	"ra_fild08": {
		"neighbors": [
			{
				"dir": "N",
				"map": "ra_fild04",
				"dst": {
					"x": 263,
					"y": 60
				},
				"edge": {
					"axis": "y",
					"at": 370,
					"cross": [
						287,
						287
					]
				},
				"offset": {
					"dx": 24,
					"dy": 310
				},
				"warps": 1
			},
			{
				"dir": "S",
				"map": "ra_fild12",
				"dst": {
					"x": 149,
					"y": 369
				},
				"edge": {
					"axis": "y",
					"at": 29,
					"cross": [
						165,
						165
					]
				},
				"offset": {
					"dx": 16,
					"dy": -340
				},
				"warps": 1
			}
		]
	},
	"ra_fild10": {
		"neighbors": [
			{
				"dir": "E",
				"map": "ra_fild11",
				"dst": {
					"x": 28,
					"y": 290
				},
				"edge": {
					"axis": "x",
					"at": 384,
					"cross": [
						287,
						287
					]
				},
				"offset": {
					"dx": 356,
					"dy": -3
				},
				"warps": 1
			}
		]
	},
	"ra_fild11": {
		"neighbors": [
			{
				"dir": "W",
				"map": "ra_fild10",
				"dst": {
					"x": 379,
					"y": 283
				},
				"edge": {
					"axis": "x",
					"at": 21,
					"cross": [
						290,
						290
					]
				},
				"offset": {
					"dx": -358,
					"dy": 7
				},
				"warps": 1
			}
		]
	},
	"ra_fild12": {
		"neighbors": [
			{
				"dir": "N",
				"map": "ra_fild08",
				"dst": {
					"x": 165,
					"y": 36
				},
				"edge": {
					"axis": "y",
					"at": 374,
					"cross": [
						149,
						149
					]
				},
				"offset": {
					"dx": -16,
					"dy": 338
				},
				"warps": 1
			}
		]
	},
	"spl_fild01": {
		"neighbors": [
			{
				"dir": "S",
				"map": "spl_fild02",
				"dst": {
					"x": 292,
					"y": 377
				},
				"edge": {
					"axis": "y",
					"at": 28,
					"cross": [
						289,
						289
					]
				},
				"offset": {
					"dx": -3,
					"dy": -349
				},
				"warps": 1
			}
		]
	},
	"spl_fild02": {
		"neighbors": [
			{
				"dir": "S",
				"map": "spl_fild03",
				"dst": {
					"x": 306,
					"y": 376
				},
				"edge": {
					"axis": "y",
					"at": 10,
					"cross": [
						103,
						310
					]
				},
				"offset": {
					"dx": 4,
					"dy": -366
				},
				"warps": 2
			},
			{
				"dir": "N",
				"map": "spl_fild01",
				"dst": {
					"x": 289,
					"y": 30
				},
				"edge": {
					"axis": "y",
					"at": 379,
					"cross": [
						293,
						293
					]
				},
				"offset": {
					"dx": 4,
					"dy": 349
				},
				"warps": 1
			}
		]
	},
	"spl_fild03": {
		"neighbors": [
			{
				"dir": "N",
				"map": "spl_fild02",
				"dst": {
					"x": 102,
					"y": 32
				},
				"edge": {
					"axis": "y",
					"at": 373,
					"cross": [
						99,
						306
					]
				},
				"offset": {
					"dx": -3,
					"dy": 341
				},
				"warps": 2
			}
		]
	},
	"um_fild01": {
		"neighbors": [
			{
				"dir": "E",
				"map": "um_fild02",
				"dst": {
					"x": 25,
					"y": 272
				},
				"edge": {
					"axis": "x",
					"at": 369,
					"cross": [
						277,
						277
					]
				},
				"offset": {
					"dx": 344,
					"dy": 5
				},
				"warps": 1
			}
		]
	},
	"um_fild02": {
		"neighbors": [
			{
				"dir": "W",
				"map": "um_fild01",
				"dst": {
					"x": 366,
					"y": 277
				},
				"edge": {
					"axis": "x",
					"at": 22,
					"cross": [
						272,
						272
					]
				},
				"offset": {
					"dx": -344,
					"dy": -5
				},
				"warps": 1
			},
			{
				"dir": "N",
				"map": "um_fild04",
				"dst": {
					"x": 182,
					"y": 16
				},
				"edge": {
					"axis": "y",
					"at": 374,
					"cross": [
						188,
						188
					]
				},
				"offset": {
					"dx": 6,
					"dy": 358
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "um_fild03",
				"dst": {
					"x": 23,
					"y": 334
				},
				"edge": {
					"axis": "x",
					"at": 373,
					"cross": [
						148,
						329
					]
				},
				"offset": {
					"dx": 350,
					"dy": -5
				},
				"warps": 2
			}
		]
	},
	"um_fild03": {
		"neighbors": [
			{
				"dir": "W",
				"map": "um_fild02",
				"dst": {
					"x": 370,
					"y": 329
				},
				"edge": {
					"axis": "x",
					"at": 19,
					"cross": [
						145,
						334
					]
				},
				"offset": {
					"dx": -351,
					"dy": 5
				},
				"warps": 2
			},
			{
				"dir": "S",
				"map": "cmd_fild01",
				"dst": {
					"x": 74,
					"y": 363
				},
				"edge": {
					"axis": "y",
					"at": 50,
					"cross": [
						114,
						243
					]
				},
				"offset": {
					"dx": 40,
					"dy": -313
				},
				"warps": 2
			}
		]
	},
	"um_fild04": {
		"neighbors": [
			{
				"dir": "S",
				"map": "um_fild02",
				"dst": {
					"x": 190,
					"y": 371
				},
				"edge": {
					"axis": "y",
					"at": 13,
					"cross": [
						182,
						182
					]
				},
				"offset": {
					"dx": -8,
					"dy": -358
				},
				"warps": 1
			}
		]
	},
	"ve_fild01": {
		"neighbors": [
			{
				"dir": "E",
				"map": "ve_fild02",
				"dst": {
					"x": 36,
					"y": 263
				},
				"edge": {
					"axis": "x",
					"at": 366,
					"cross": [
						92,
						267
					]
				},
				"offset": {
					"dx": 330,
					"dy": 4
				},
				"warps": 2
			},
			{
				"dir": "S",
				"map": "ve_fild04",
				"dst": {
					"x": 174,
					"y": 334
				},
				"edge": {
					"axis": "y",
					"at": 20,
					"cross": [
						184,
						184
					]
				},
				"offset": {
					"dx": 10,
					"dy": -314
				},
				"warps": 1
			}
		]
	},
	"ve_fild02": {
		"neighbors": [
			{
				"dir": "W",
				"map": "ve_fild01",
				"dst": {
					"x": 361,
					"y": 267
				},
				"edge": {
					"axis": "x",
					"at": 31,
					"cross": [
						133,
						263
					]
				},
				"offset": {
					"dx": -330,
					"dy": -4
				},
				"warps": 2
			}
		]
	},
	"ve_fild03": {
		"neighbors": [
			{
				"dir": "E",
				"map": "ve_fild04",
				"dst": {
					"x": 49,
					"y": 249
				},
				"edge": {
					"axis": "x",
					"at": 355,
					"cross": [
						223,
						223
					]
				},
				"offset": {
					"dx": 306,
					"dy": -26
				},
				"warps": 1
			}
		]
	},
	"ve_fild04": {
		"neighbors": [
			{
				"dir": "N",
				"map": "ve_fild01",
				"dst": {
					"x": 184,
					"y": 25
				},
				"edge": {
					"axis": "y",
					"at": 339,
					"cross": [
						174,
						174
					]
				},
				"offset": {
					"dx": -10,
					"dy": 314
				},
				"warps": 1
			},
			{
				"dir": "W",
				"map": "ve_fild03",
				"dst": {
					"x": 350,
					"y": 220
				},
				"edge": {
					"axis": "x",
					"at": 44,
					"cross": [
						249,
						249
					]
				},
				"offset": {
					"dx": -306,
					"dy": 29
				},
				"warps": 1
			},
			{
				"dir": "S",
				"map": "ve_fild06",
				"dst": {
					"x": 80,
					"y": 183
				},
				"edge": {
					"axis": "y",
					"at": 50,
					"cross": [
						115,
						115
					]
				},
				"offset": {
					"dx": 35,
					"dy": -133
				},
				"warps": 1
			}
		]
	},
	"ve_fild06": {
		"neighbors": [
			{
				"dir": "N",
				"map": "ve_fild04",
				"dst": {
					"x": 115,
					"y": 55
				},
				"edge": {
					"axis": "y",
					"at": 177,
					"cross": [
						81,
						81
					]
				},
				"offset": {
					"dx": -34,
					"dy": 122
				},
				"warps": 1
			}
		]
	},
	"yuno_fild01": {
		"neighbors": [
			{
				"dir": "W",
				"map": "yuno_fild12",
				"dst": {
					"x": 373,
					"y": 239
				},
				"edge": {
					"axis": "x",
					"at": 26,
					"cross": [
						246,
						246
					]
				},
				"offset": {
					"dx": -347,
					"dy": 7
				},
				"warps": 1
			},
			{
				"dir": "N",
				"map": "yuno_fild09",
				"dst": {
					"x": 70,
					"y": 19
				},
				"edge": {
					"axis": "y",
					"at": 378,
					"cross": [
						70,
						286
					]
				},
				"offset": {
					"dx": 0,
					"dy": 359
				},
				"warps": 2
			}
		]
	},
	"yuno_fild02": {
		"neighbors": [
			{
				"dir": "W",
				"map": "yuno_fild03",
				"dst": {
					"x": 381,
					"y": 331
				},
				"edge": {
					"axis": "x",
					"at": 18,
					"cross": [
						337,
						337
					]
				},
				"offset": {
					"dx": -363,
					"dy": 6
				},
				"warps": 1
			},
			{
				"dir": "S",
				"map": "yuno_fild08",
				"dst": {
					"x": 74,
					"y": 374
				},
				"edge": {
					"axis": "y",
					"at": 23,
					"cross": [
						70,
						294
					]
				},
				"offset": {
					"dx": -4,
					"dy": -351
				},
				"warps": 2
			},
			{
				"dir": "N",
				"map": "hu_fild04",
				"dst": {
					"x": 122,
					"y": 35
				},
				"edge": {
					"axis": "y",
					"at": 375,
					"cross": [
						117,
						117
					]
				},
				"offset": {
					"dx": -5,
					"dy": 340
				},
				"warps": 1
			}
		]
	},
	"yuno_fild03": {
		"neighbors": [
			{
				"dir": "E",
				"map": "yuno_fild02",
				"dst": {
					"x": 20,
					"y": 337
				},
				"edge": {
					"axis": "x",
					"at": 383,
					"cross": [
						331,
						331
					]
				},
				"offset": {
					"dx": 363,
					"dy": -6
				},
				"warps": 1
			},
			{
				"dir": "W",
				"map": "yuno_fild04",
				"dst": {
					"x": 373,
					"y": 84
				},
				"edge": {
					"axis": "x",
					"at": 19,
					"cross": [
						79,
						155
					]
				},
				"offset": {
					"dx": -354,
					"dy": -5
				},
				"warps": 2
			},
			{
				"dir": "S",
				"map": "yuno_fild07",
				"dst": {
					"x": 179,
					"y": 352
				},
				"edge": {
					"axis": "y",
					"at": 15,
					"cross": [
						179,
						179
					]
				},
				"offset": {
					"dx": 0,
					"dy": -337
				},
				"warps": 1
			},
			{
				"dir": "N",
				"map": "yuno_fild06",
				"dst": {
					"x": 218,
					"y": 33
				},
				"edge": {
					"axis": "y",
					"at": 382,
					"cross": [
						215,
						215
					]
				},
				"offset": {
					"dx": -3,
					"dy": 349
				},
				"warps": 1
			}
		]
	},
	"yuno_fild04": {
		"neighbors": [
			{
				"dir": "E",
				"map": "yuno_fild03",
				"dst": {
					"x": 21,
					"y": 79
				},
				"edge": {
					"axis": "x",
					"at": 375,
					"cross": [
						84,
						150
					]
				},
				"offset": {
					"dx": 354,
					"dy": 5
				},
				"warps": 2
			},
			{
				"dir": "S",
				"map": "ein_fild06",
				"dst": {
					"x": 252,
					"y": 363
				},
				"edge": {
					"axis": "y",
					"at": 21,
					"cross": [
						251,
						251
					]
				},
				"offset": {
					"dx": -1,
					"dy": -342
				},
				"warps": 1
			}
		]
	},
	"yuno_fild06": {
		"neighbors": [
			{
				"dir": "S",
				"map": "yuno_fild03",
				"dst": {
					"x": 215,
					"y": 375
				},
				"edge": {
					"axis": "y",
					"at": 27,
					"cross": [
						214,
						214
					]
				},
				"offset": {
					"dx": -1,
					"dy": -348
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "hu_fild04",
				"dst": {
					"x": 34,
					"y": 126
				},
				"edge": {
					"axis": "x",
					"at": 369,
					"cross": [
						132,
						132
					]
				},
				"offset": {
					"dx": 335,
					"dy": 6
				},
				"warps": 1
			},
			{
				"dir": "N",
				"map": "hu_fild01",
				"dst": {
					"x": 135,
					"y": 42
				},
				"edge": {
					"axis": "y",
					"at": 370,
					"cross": [
						151,
						151
					]
				},
				"offset": {
					"dx": 16,
					"dy": 328
				},
				"warps": 1
			}
		]
	},
	"yuno_fild07": {
		"neighbors": [
			{
				"dir": "S",
				"map": "yuno_fild11",
				"dst": {
					"x": 92,
					"y": 369
				},
				"edge": {
					"axis": "y",
					"at": 12,
					"cross": [
						92,
						92
					]
				},
				"offset": {
					"dx": 0,
					"dy": -357
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "yuno_fild08",
				"dst": {
					"x": 22,
					"y": 278
				},
				"edge": {
					"axis": "x",
					"at": 354,
					"cross": [
						72,
						291
					]
				},
				"offset": {
					"dx": 332,
					"dy": 13
				},
				"warps": 2
			},
			{
				"dir": "N",
				"map": "yuno_fild03",
				"dst": {
					"x": 179,
					"y": 17
				},
				"edge": {
					"axis": "y",
					"at": 354,
					"cross": [
						179,
						179
					]
				},
				"offset": {
					"dx": 0,
					"dy": 337
				},
				"warps": 1
			},
			{
				"dir": "W",
				"map": "ein_fild06",
				"dst": {
					"x": 338,
					"y": 170
				},
				"edge": {
					"axis": "x",
					"at": 73,
					"cross": [
						76,
						219
					]
				},
				"offset": {
					"dx": -265,
					"dy": 49
				},
				"warps": 2
			}
		]
	},
	"yuno_fild08": {
		"neighbors": [
			{
				"dir": "S",
				"map": "yuno_fild12",
				"dst": {
					"x": 195,
					"y": 371
				},
				"edge": {
					"axis": "y",
					"at": 21,
					"cross": [
						145,
						145
					]
				},
				"offset": {
					"dx": -50,
					"dy": -350
				},
				"warps": 1
			},
			{
				"dir": "E",
				"map": "yuno_fild09",
				"dst": {
					"x": 21,
					"y": 194
				},
				"edge": {
					"axis": "x",
					"at": 376,
					"cross": [
						193,
						193
					]
				},
				"offset": {
					"dx": 355,
					"dy": -1
				},
				"warps": 1
			},
			{
				"dir": "W",
				"map": "yuno_fild07",
				"dst": {
					"x": 352,
					"y": 291
				},
				"edge": {
					"axis": "x",
					"at": 20,
					"cross": [
						58,
						278
					]
				},
				"offset": {
					"dx": -332,
					"dy": -13
				},
				"warps": 2
			},
			{
				"dir": "N",
				"map": "yuno_fild02",
				"dst": {
					"x": 70,
					"y": 25
				},
				"edge": {
					"axis": "y",
					"at": 376,
					"cross": [
						74,
						286
					]
				},
				"offset": {
					"dx": 4,
					"dy": 351
				},
				"warps": 2
			}
		]
	},
	"yuno_fild09": {
		"neighbors": [
			{
				"dir": "S",
				"map": "yuno_fild01",
				"dst": {
					"x": 70,
					"y": 376
				},
				"edge": {
					"axis": "y",
					"at": 17,
					"cross": [
						70,
						280
					]
				},
				"offset": {
					"dx": 0,
					"dy": -359
				},
				"warps": 2
			},
			{
				"dir": "W",
				"map": "yuno_fild08",
				"dst": {
					"x": 374,
					"y": 193
				},
				"edge": {
					"axis": "x",
					"at": 19,
					"cross": [
						194,
						194
					]
				},
				"offset": {
					"dx": -355,
					"dy": 1
				},
				"warps": 1
			}
		]
	},
	"yuno_fild11": {
		"neighbors": [
			{
				"dir": "E",
				"map": "yuno_fild12",
				"dst": {
					"x": 25,
					"y": 338
				},
				"edge": {
					"axis": "x",
					"at": 368,
					"cross": [
						218,
						361
					]
				},
				"offset": {
					"dx": 343,
					"dy": 23
				},
				"warps": 2
			},
			{
				"dir": "N",
				"map": "yuno_fild07",
				"dst": {
					"x": 92,
					"y": 14
				},
				"edge": {
					"axis": "y",
					"at": 371,
					"cross": [
						92,
						92
					]
				},
				"offset": {
					"dx": 0,
					"dy": 357
				},
				"warps": 1
			},
			{
				"dir": "W",
				"map": "ein_fild07",
				"dst": {
					"x": 380,
					"y": 263
				},
				"edge": {
					"axis": "x",
					"at": 28,
					"cross": [
						266,
						266
					]
				},
				"offset": {
					"dx": -352,
					"dy": 3
				},
				"warps": 1
			}
		]
	},
	"yuno_fild12": {
		"neighbors": [
			{
				"dir": "E",
				"map": "yuno_fild01",
				"dst": {
					"x": 28,
					"y": 246
				},
				"edge": {
					"axis": "x",
					"at": 375,
					"cross": [
						239,
						239
					]
				},
				"offset": {
					"dx": 347,
					"dy": -7
				},
				"warps": 1
			},
			{
				"dir": "W",
				"map": "yuno_fild11",
				"dst": {
					"x": 366,
					"y": 361
				},
				"edge": {
					"axis": "x",
					"at": 23,
					"cross": [
						225,
						338
					]
				},
				"offset": {
					"dx": -343,
					"dy": -23
				},
				"warps": 2
			},
			{
				"dir": "N",
				"map": "yuno_fild08",
				"dst": {
					"x": 143,
					"y": 21
				},
				"edge": {
					"axis": "y",
					"at": 371,
					"cross": [
						193,
						193
					]
				},
				"offset": {
					"dx": 50,
					"dy": 350
				},
				"warps": 1
			}
		]
	}
};

export default FieldAdjacency;
